CREATE DATABASE QuanLyDonDatHang;
USE QuanLyDonDatHang;

CREATE TABLE KhachHang(
MaKH      INT				AUTO_INCREMENT PRIMARY KEY,
TenKH     VARCHAR(30)		NOT NULL,
DiaChi    VARCHAR(50)		NOT NULL,
DienThoai CHAR(10)		    NOT NULL
);

CREATE TABLE NguoiDat(
id   INT				AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30)		NOT NULL,
MaKH INT,
FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) 
);

CREATE TABLE SanPham(
MaSP INT				AUTO_INCREMENT PRIMARY KEY,
TenSP VARCHAR(20)		NOT NULL,
DonVi VARCHAR(10)		DEFAULT"Don vi",
MoTa  VARCHAR(50)
);

CREATE TABLE DatHang(
SoDH INT 				AUTO_INCREMENT PRIMARY KEY,
NgayDat DATE			NOT NULL,
SoLuong INT				NOT NULL		CHECK (SoLuong > 0),
MaSp INT,
id INT,
FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP),
FOREIGN KEY (id) REFERENCES NguoiDat(id)
);

CREATE TABLE NguoiGiao(
MaNG INT				AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30)		NOT NULL
);

CREATE TABLE NoiGiao(
MaDDG INT				AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50)		NOT NULL
);

CREATE TABLE NguoiNhan(
MaNN INT 				AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30)		NOT NULL,
MaKH INT,
FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
);

CREATE TABLE GiaoHang(
SoDG     INT			AUTO_INCREMENT PRIMARY KEY,
NgayGiao DATE			NOT NULL,
SoLuong  INT			NOT NULL		CHECK (SoLuong > 0),
DonGia	 INT			NOT NULL		CHECK (DonGia > 0),
MaSP     INT,
MaNN     INT,
MaDDG    INT,
MaNG     INT,
FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP),
FOREIGN KEY (MaNN) REFERENCES NguoiNhan(MaNN),
FOREIGN KEY (MaDDG) REFERENCES NoiGiao(MaDDG),
FOREIGN KEY (MaNG) REFERENCES NguoiGiao(MaNG)
);